### ISSUE TITLE
Make gene-cnv-page.component

### ISSUE THREAD

**Issue by forwardadvance** [forwardadvance/ddr_mine_browser#4]
The gene-cnv-page.component is currently just a placeholder. Please implement it.

Use the gene-mutation-page component as a base. Subscribe to the CnvService rather than the MutationService, then ender the data initially as `{{cnvs | json}}`.

**Comment by forwardadvance** [comment]
You might like to look at the table headings for http://ddrmine.lifesci.sussex.ac.uk/ddrmine/search.php?srch-term=tp53, then try to copy them.

**Comment by abercon** [comment]
Hey, do  we want a histogram or violin plot for the cnv page?
